# Generated by Django 2.1 on 2018-08-19 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnumValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255, null=True)),
                ('primitiveType', models.CharField(blank=True, choices=[('1', 'text'), ('2', 'number'), ('3', 'date'), ('4', 'enum')], default='1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255, null=True)),
                ('fieldType', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='risk.FieldType')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.Risk')),
            ],
        ),
        migrations.AddField(
            model_name='enumvalue',
            name='riskField',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.RiskField'),
        ),
    ]
