# Generated by Django 2.1 on 2018-08-19 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_auto_20180819_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskfield',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riskFields', to='risk.Risk'),
        ),
    ]
