# Generated by Django 2.1 on 2018-08-19 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_auto_20180819_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enumvalue',
            name='riskField',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldsValues', to='risk.RiskField'),
        ),
    ]
