from risk.models import *
automobileRisk = Risk(name='Automobile', description='Automobile risk')
automobileRisk.save()

automobileRiskField = RiskField(name='Brand', risk=automobileRisk, fieldType='1')
automobileRiskField.save()
automobileRiskField2 = RiskField(name='Year', risk=automobileRisk, fieldType='2')
automobileRiskField2.save()
automobileRiskField3 = RiskField(name='First Owner', risk=automobileRisk, fieldType='4')
automobileRiskField3.save()
automobileRiskFirstOwnerYesValue = EnumValue(riskField=automobileRiskField3, value='Yes')
automobileRiskFirstOwnerYesValue.save()
automobileRiskFirstOwnerNoValue = EnumValue(riskField=automobileRiskField3, value='No')
automobileRiskFirstOwnerNoValue.save()


houseRisk = Risk(name='House', description='House risk')
houseRisk.save()
houseRiskField = RiskField(name='Address', risk=houseRisk, fieldType='1')
houseRiskField.save()
houseRiskField2 = RiskField(name='Years', risk=houseRisk, fieldType='2')
houseRiskField2.save()
houseRiskField3 = RiskField(name='First Owner', risk=houseRisk, fieldType='4')
houseRiskField3.save()
firstOwnerYesValue = EnumValue(riskField=houseRiskField3, value='Yes')
firstOwnerYesValue.save()
firstOwnerNoValue = EnumValue(riskField=houseRiskField3, value='No')
firstOwnerNoValue.save()
houseRiskField4 = RiskField(name='Insurance Expiring Date', risk=houseRisk, fieldType='3')
houseRiskField4.save()